### ISSUE TITLE
Peer Dependency Error

### ISSUE THREAD

**Issue by paul-barry-kenzan** [prodatakey/dirty-chai#10]
I'm receiving a peer dependency error when attempting to install karma-dirty-chai. I know that the karma plugin is ultimately a wrapper for dirty-chai. Any input on how to best resolve the errors below?

Thanks.

*The peer dependency chai@<1.10.0 || >1.10.0 <3 included from karma-dirty-chai will no longer be automatically installed to fulfill the peerDependency in npm 3+. Your application will need to depend on it explicitly.*

*The peer dependency dirty-chai@^1.2.0 included from karma-dirty-chai will no longer be automatically installed to fulfill the peerDependency in npm 3+. Your application will need to depend on it explicitly.*

**Comment by seanstrom** [comment]
NPM is warning you about [peerDependencies](https://nodejs.org/en/blog/npm/peer-dependencies/)
Specifically how they won't be installed automatically in NPM 3. 
The solution is to explicitly depend on `chai` and `dirty-chai` in your `package.json`.
