### ISSUE TITLE
Support Chai 4.0

### ISSUE THREAD

**Issue by Shockolate** [prodatakey/dirty-chai#23]
Looks like this is trying to be solved with #22

**Comment by evantahler** [comment]
To add some context, the current error occurs on `npm install`, as the peer dependancies require a chai version of 3.x 

https://github.com/prodatakey/dirty-chai/blob/master/package.json#L39

**Comment by Shockolate** [comment]
I'm personally willing to look into a solution, but it looks like there are 2 PR's up for it :)

**Comment by joshperry** [comment]
Merged in v2.0.0! Enjoy
