### ISSUE TITLE
Feature request - add falsy/truthy

### ISSUE THREAD

**Issue by alesmenzelsocialbakers** [prodatakey/dirty-chai#33]
It would be nice to add falsy/truthy aliases instead `.is.ok()` and `.is.not.ok()` which are in my honest opinion very confusing
(i.e. consider `expect(error).to.be.not.ok()` and instead `expect(error).to.be.falsy()`)

See: https://github.com/chaijs/chai/issues/235

**Comment by joshperry** [comment]
Hi @alesmenzelsocialbakers,

I don't disagree with your sentiment. Unfortunately, this plugin's only purpose is to expose the chai terminating properties as functions, instead. We have no plans to modify any of the chai proper interface.

Thank you for the suggestion!
