### ISSUE TITLE
How do I use this? Is it a drop in replacement for chai?

### ISSUE THREAD

**Issue by stevemao** [prodatakey/dirty-chai#9]
if I do
```js
var chai = require("dirty-chai")
```
It doesn't work.

**Comment by zamnuts** [comment]
dirty-chai is a plugin for chai, usage:

```javascript
var chai = require('chai'),
    dirtyChai = require('dirty-chai'),
    expect = chai.expect;
chai.use(dirtyChai);

// ...
expect(true).to.be.true();
// ...
```

**Comment by gasi** [comment]
@zamnuts Thanks for explaining. Would you mind adding this to the README or make it easier to just use `dirty-chai` as drop-in replacement for `chai`, i.e. `var {expect} = require('dirty-chai')`?

**Comment by aseemk** [comment]
+1 for a drop-in replacement. That'd be great!

**Comment by zamnuts** [comment]
@gasi @aseemk One could publish a NPM module as a drop-in replacement (meh...), or you could just do the one liner:

```javascript
var chai = require('chai').use(require('dirty-chai'));
```

Usage:
```javascript
var chai = require('chai').use(require('dirty-chai')),
    expect = chai.expect; // still need this unless you wanna chai.expect all day.

//...
expect(true).to.be.true();
//...
```

Or better yet, if you want to just get your hands on expect:

```javascript
var expect = require('chai').use(require('dirty-chai')).expect;
```

**Comment by gasi** [comment]
@zamnuts Cool! You should add it to README :smile:

**Comment by levithomason** [comment]
Updated README in #13
